version: '3.8'

volumes:
  pg-data:

services:
  postgres:
    image: postgres:12.7-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  app:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_PASSWORD=postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres

  proxy:
    image: nginx:1.11
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/main/resources/static:/data/static/